name: Pylint Code Quality Check

on:
  push:  # Trigger on every push to any branch
    branches:
      - "**"  # This pattern means any branch

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint
        run: |
          pylint app/ || true  # Ensure the job doesn't fail